In [234]:
import torch
import torch.nn as nn
import torch.functional as F

In [235]:
'''
77
63
1399.2022092666462
1141.454433875422
5.098938019445958
0.02664452415889013
15.058951381832024
1.8832796447711142
31907.70371130618
2006.7752980301982
Marcin

199
290
3050.8474576271187
4453.004622496148
7.825804287618923
0.006988225731965805
14.108660590920106
1.1760921635070218
37948.75770738181
1328.5310107306827
Bartek
'''

'\n77\n63\n1399.2022092666462\n1141.454433875422\n5.098938019445958\n0.02664452415889013\n15.058951381832024\n1.8832796447711142\n31907.70371130618\n2006.7752980301982\nMarcin\n\n199\n290\n3050.8474576271187\n4453.004622496148\n7.825804287618923\n0.006988225731965805\n14.108660590920106\n1.1760921635070218\n37948.75770738181\n1328.5310107306827\nBartek\n'

In [236]:
class Network(nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.fc1 = nn.Linear(in_features=10, out_features=10, bias=True)
        self.fc2 = nn.Linear(in_features=10, out_features=10, bias=True)
        self.out = nn.Linear(in_features=10, out_features = 4, bias=True)
        
    def forward(self, t):
        #1st layer
        t = self.fc1(t)
        #2nd layer
        t = self.fc2(t)
        #output layer
        t = self.out(t)
        
        return t

In [237]:
marcin = torch.tensor([77, 63, 1399.2022092666462, 1141.454433875422, 5.098938019445958, 0.02664452415889013, 15.058951381832024, 1.8832796447711142, 31907.70371130618, 2006.7752980301982])
network=Network()
output = network(marcin)
print(output)

tensor([-1973.5437, -1684.8969,  1971.0435,  4173.2573],
       grad_fn=<AddBackward0>)


In [238]:
network.zero_grad()
#output.backward(torch.randn(1, 4))

In [239]:
target = torch.tensor([1., 0, 0, 0])
print(target)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)
retain_graph=True

tensor([1., 0., 0., 0.])
tensor(7009697.5000, grad_fn=<MseLossBackward>)


In [240]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('fc1.bias.grad before backward')
print(network.fc1.bias.grad)

loss.backward()

print('fc1.bias.grad after backward')
print(network.fc1.bias.grad)

fc1.bias.grad before backward
None
fc1.bias.grad after backward
tensor([-232.6610, -177.5616,  188.8595, -771.8677, -516.2960, -482.7094,
        -291.3752,   48.0264,  370.6012,  -77.4006])


In [241]:
weight_matrix = torch.randn(10)
weight_matrix

tensor([ 0.9917, -0.4610,  2.0100, -0.5791,  0.3101, -1.5584,  0.2548, -1.4310,
         0.6763, -0.7614])

In [242]:
fc1.weight

Parameter containing:
tensor([[-0.2195, -0.1896, -0.2759,  0.0248,  0.0210, -0.3044, -0.0660,  0.2692,
          0.0787,  0.2383],
        [ 0.2075, -0.2050, -0.2800, -0.1502, -0.0662,  0.1297, -0.0074,  0.0032,
         -0.0211, -0.2649],
        [-0.2199,  0.1409,  0.2518, -0.2291, -0.0385, -0.2414,  0.0864,  0.2444,
         -0.3075,  0.2506],
        [-0.2457,  0.2811, -0.0656, -0.0464, -0.0109, -0.1694,  0.0350,  0.1079,
         -0.1484,  0.2092],
        [-0.0099,  0.2479, -0.2232, -0.0566, -0.1631, -0.1010,  0.2711,  0.3062,
          0.1290, -0.1580],
        [-0.2662,  0.2456,  0.0395,  0.3140, -0.1381,  0.2263, -0.1938, -0.2007,
          0.2873, -0.2983],
        [-0.2751,  0.1945, -0.1042,  0.1424,  0.2322,  0.2511,  0.0484,  0.1009,
          0.0994,  0.0686],
        [-0.2440,  0.2157,  0.1581, -0.2903,  0.1565, -0.0459,  0.2166,  0.2880,
          0.1784,  0.0509],
        [ 0.0218,  0.2297, -0.0904,  0.1244, -0.0564,  0.0089,  0.1349, -0.0928,
         -0.0710,  0.0758